### ISSUE TITLE
How do I change the URL?

### ISSUE THREAD

**Issue by agamerj** [ParveenBhadooOfficial/web.telegram.org#4]
Hello, there are certain sub-domains which are blocked. How do I change them (from Venus to something else)?

![sx-22-February-20-3064](https://user-images.githubusercontent.com/9323342/75062351-a7b55680-5508-11ea-815d-09c68e668f07.png)

**Comment by ParveenBhadooOfficial** [comment]
already change in this repo.

**Comment by agamerj** [comment]
I'm asking for the knowledge, where can we change it?

**Comment by ParveenBhadooOfficial** [comment]
EDIT https://github.com/ParveenBhadooOfficial/web.telegram.org/blob/master/js/app.js
